export const vertexShader = `
precision highp float;
attribute vec3 aPosition;
attribute float aSize;
attribute float aBrightness;
attribute float aPhase;
attribute float aTemperature;
attribute float aGroup;
uniform vec2 uResolution;
uniform vec2 uPointer;
uniform vec2 uRotation;
uniform float uTime;
uniform float uIntro;
uniform float uPresence;
uniform float uDpr;
uniform float uScroll;
varying float vBrightness;
varying float vTemperature;
varying float vLarge;
varying float vCentral;
void main() {
  vec3 p = aPosition;
  float field = aGroup;
  float away = smoothstep(.02, .92, uScroll);
  float scatterAngle = aPhase * 3.0;
  float scatterRadius = .95 + fract(aPhase * 13.17) * .9;
  vec3 dispersed = vec3(cos(scatterAngle) * scatterRadius, sin(scatterAngle) * scatterRadius, p.z);
  p = mix(p, dispersed, away * field);
  float settle = 1.0 - pow(1.0 - uIntro, 3.0);
  float swirl = (1.0-settle) * (3.2 + aPhase * 0.14);
  float breathe = sin(uTime * 0.23 + aPhase) * 0.001;
  p.xy += vec2(cos(aPhase+uTime*.045), sin(aPhase+uTime*.035)) * (0.002 + (1.0-field)*.005);
  float c = cos(swirl), s = sin(swirl);
  p.xy = mix(p.xy, mat2(c,-s,s,c) * p.xy * mix(2.8, 1.0, settle), field);
  float cy = cos(uRotation.x), sy = sin(uRotation.x);
  float cx = cos(uRotation.y), sx = sin(uRotation.y);
  p.xz = mat2(cy,-sy,sy,cy) * p.xz;
  p.yz = mat2(cx,-sx,sx,cx) * p.yz;
  float roll = -.62 * field;
  p.xy = mat2(cos(roll),-sin(roll),sin(roll),cos(roll)) * p.xy;
  float perspective = 2.8 / (2.8 - p.z * .5);
  float aspect = uResolution.x / uResolution.y;
  float shapeScale = min(1.0, aspect / .95);
  p.x *= mix(1.0, 1.0 / aspect * shapeScale, field);
  p.y *= mix(1.0, shapeScale, field);
  p.xy *= perspective;
  p.y += breathe * field + uScroll * .18 * (p.z + .6);
  vec2 delta = p.xy-uPointer;
  delta.x *= aspect;
  float distanceToPointer = length(delta);
  float facing = abs(cy * cx);
  float force = exp(-distanceToPointer*distanceToPointer*36.0) * uPresence * facing;
  vec2 direction = delta / max(distanceToPointer, .015);
  direction.x /= aspect;
  p.xy += direction * force * .018;
  p.xy += uPointer * (.008+p.z*.014) * uPresence * facing;
  gl_Position = vec4(p.xy, 0.0, 1.0);
  vLarge = smoothstep(2.0, 4.0, aSize);
  gl_PointSize = max(1.0, aSize * uDpr * (1.8 + vLarge * 6.8) * perspective) * 1.1664;
  vBrightness = aBrightness * (.86 + .14*sin(uTime*.65+aPhase)) * mix(.5,1.0,settle) * mix(1.0, .40, away * field) * mix(1.0, .5 + .5 * sqrt(facing), field);
  vTemperature = aTemperature;
  vCentral = (1.0 - smoothstep(.06, .23, length(aPosition.xy))) * field;
  vBrightness *= mix(1.0, .55, vCentral) * 1.08;
}
`;

export const fragmentShader = `
precision mediump float;
varying float vBrightness;
varying float vTemperature;
varying float vLarge;
varying float vCentral;
void main() {
  vec2 uv = gl_PointCoord - .5;
  float r = length(uv) * 2.0;
  if(r > 1.0) discard;
  vec3 cold = vec3(.43,.75,1.0);
  vec3 warm = vec3(1.0,.52,.24);
  vec3 color = vTemperature < .72 ? mix(cold, vec3(.94,.98,1.0),vTemperature/.72) : mix(vec3(1.0,.87,.72),warm,(vTemperature-.72)/.28);
  float smallCore = exp(-r*r*8.0);
  float core = exp(-r*r*110.0);
  float bloom = exp(-r*r*9.0)*.18;
  float halo = exp(-r*r*3.0)*.027;
  float rays = (exp(-abs(uv.x)*130.0)+exp(-abs(uv.y)*130.0)) * exp(-r*8.0)*.12;
  float alpha = mix(smallCore,core+bloom+halo+rays,vLarge) * vBrightness;
  color = mix(color,vec3(1.0),core*.78*vLarge);
  gl_FragColor = vec4(color,alpha);
}
`;
